<?php
 
/*
 * Implementation of hook_menu()
 */
function custom_menu_concept_menu(){
  $items['theme_menu_concept'] = array(
    'title' => 'Page Title',  // page title
    'description' => 'Simple custom hook_menu() implementation.', // describe the page for the menu system.visitors will not see this
    'page callback' => 'my_page_function', // function that is called when visiting the new path
    'access arguments' => array('access content'),  // permissions required to view page
  );  
  return $items;
}

/*
 * Returns custom content to Drupal, callback
 */
function my_page_function(){
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node');
  $query->entityCondition('bundle', 'page');
  $query->propertyCondition('status', 1);
  $query->propertyOrderBy('created', 'DESC');
  $query->range(0, 5); 
  $result = $query->execute();

  if (isset($result['node'])) {
    $article_nids = array_keys($result['node']);
    $nodes = entity_load('node', $article_nids);
  }
  return theme('custom_page', array('nodes' => $nodes));
  //return $block;         
}
   
/*
 * Implementation of hook_theme().
 */
function custom_menu_concept_theme(){
  return array(
    'custom_page' => array(
    'template' => 'custom-page',
    'variables' => array('nodes' => NULL),
    ),
  );
}

/*
 * Preprocess function for custom template.
 */
function custom_menu_concept_preprocess_custom_page(&$vars) {
  foreach($vars['nodes'] as $node) {
    $vars['node_title'] .= $node->title.'</br>';
  }
}

